id = "autohotkey"
name = "AutoHotkey"
version = "0.1.0"
schema_version = 1
authors = ["Alfredo Menezes"]
description = "AutoHotkey v1 language support for Zed"
repository = "https://github.com/alfredomtx/tree-sitter-autohotkey"

[grammars.autohotkey]
repository = "https://github.com/alfredomtx/tree-sitter-autohotkey"
rev = "8d3632bb4a2378911552ac6edc8f53ca79bf6560"
path = "."

[language_servers.autohotkey-lsp]
name = "AutoHotkey Language Server"
languages = ["AutoHotkey"]
