id = "autohotkey"
name = "AutoHotkey"
version = "0.1.0"
schema_version = 1
authors = ["Alfredo Menezes"]
description = "AutoHotkey v1 language support for Zed"
repository = "https://github.com/alfredomtx/tree-sitter-autohotkey"

[grammars.autohotkey]
repository = "https://github.com/alfredomtx/tree-sitter-autohotkey"
rev = "dbd832632c6483b66d618000ce5115650209358c"
path = "."

[language_servers.autohotkey-lsp]
name = "AutoHotkey Language Server"
languages = ["AutoHotkey"]
